{% set version = '1.8.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-checkmate
  version: {{ version|replace("-", "_") }}

source:
  fn: checkmate_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/checkmate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/checkmate/checkmate_{{ version }}.tar.gz
  sha256: e94d2a3971908ce2a8252a9320ae7e030e0364b0ecd5385ab98e600aca7cd1e0

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-backports >=1.1.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-backports >=1.1.0

test:
  commands:
    - $R -e "library('checkmate')"           # [not win]
    - "\"%R%\" -e \"library('checkmate')\""  # [win]

about:
  home: https://github.com/mllg/checkmate
  license: BSD_3_clause
  summary: Tests and assertions to perform frequent argument checks. A substantial part of the
    package was written in C to minimize any worries about execution time overhead.
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
