{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-checkmate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/checkmate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/checkmate/checkmate_{{ version }}.tar.gz
  sha256: 0dc25b0e20c04836359df1885d099c6e4ad8ae0e585a9e4107f7ea945d9c6fa4

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-backports >=1.1.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-backports >=1.1.0

test:
  commands:
    - $R -e "library('checkmate')"           # [not win]
    - "\"%R%\" -e \"library('checkmate')\""  # [win]

about:
  home: https://github.com/mllg/checkmate
  license: BSD_3_clause
  license_file: LICENSE
  summary: Tests and assertions to perform frequent argument checks. A substantial part of the
    package was written in C to minimize any worries about execution time overhead.
  license_family: BSD

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: checkmate
# Type: Package
# Title: Fast and Versatile Argument Checks
# Description: Tests and assertions to perform frequent argument checks. A substantial part of the package was written in C to minimize any worries about execution time overhead.
# Version: 1.9.1
# Authors@R: c( person("Michel", "Lang", NULL, "michellang@gmail.com", role = c("cre", "aut"), comment = c(ORCID = "0000-0001-9754-0393")), person("Bernd", "Bischl", NULL, "bernd_bischl@gmx.de", role = "ctb") )
# URL: https://github.com/mllg/checkmate
# URLNote: https://github.com/mllg/checkmate
# BugReports: https://github.com/mllg/checkmate/issues
# NeedsCompilation: yes
# ByteCompile: yes
# Encoding: UTF-8
# Depends: R (>= 3.0.0)
# Imports: backports (>= 1.1.0), utils
# Suggests: R6, bit, fastmatch, data.table (>= 1.9.8), devtools, ggplot2, knitr, magrittr, microbenchmark, rmarkdown, testthat (>= 0.11.0), tibble
# License: BSD_3_clause + file LICENSE
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Collate: 'AssertCollection.R' 'allMissing.R' 'anyInfinite.R' 'anyMissing.R' 'anyNaN.R' 'asInteger.R' 'assert.R' 'helper.R' 'makeExpectation.R' 'makeTest.R' 'makeAssertion.R' 'checkAccess.R' 'checkArray.R' 'checkAtomic.R' 'checkAtomicVector.R' 'checkBit.R' 'checkCharacter.R' 'checkChoice.R' 'checkClass.R' 'checkComplex.R' 'checkCount.R' 'checkDataFrame.R' 'checkDataTable.R' 'checkDate.R' 'checkDirectoryExists.R' 'checkDisjunct.R' 'checkDouble.R' 'checkEnvironment.R' 'checkFALSE.R' 'checkFactor.R' 'checkFileExists.R' 'checkFlag.R' 'checkFormula.R' 'checkFunction.R' 'checkInt.R' 'checkInteger.R' 'checkIntegerish.R' 'checkList.R' 'checkLogical.R' 'checkMatrix.R' 'checkMultiClass.R' 'checkNamed.R' 'checkNames.R' 'checkNull.R' 'checkNumber.R' 'checkNumeric.R' 'checkOS.R' 'checkPOSIXct.R' 'checkPathForOutput.R' 'checkR6.R' 'checkRaw.R' 'checkScalar.R' 'checkScalarNA.R' 'checkSetEqual.R' 'checkString.R' 'checkSubset.R' 'checkTRUE.R' 'checkTibble.R' 'checkVector.R' 'coalesce.R' 'isIntegerish.R' 'matchArg.R' 'qassert.R' 'qassertr.R' 'vname.R' 'wfwl.R' 'zzz.R'
# Packaged: 2019-01-15 15:49:07 UTC; lang
# Author: Michel Lang [cre, aut] (<https://orcid.org/0000-0001-9754-0393>), Bernd Bischl [ctb]
# Maintainer: Michel Lang <michellang@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-01-15 16:20:03 UTC
