travis:
  secure:
    BINSTAR_TOKEN: gBcx25dnWoZiDWcbRO57PISLIq95BDOUprB8V2bSQAkfZCPWinSMqnfyZQVy5LvAC3hgvZ1H3NMDtmxGBv/CAvANVTQFAMfJuHU0vDsLn+HRvXBPFCRqhu2rma0/kdFUavbMHOl97R7T/I91Np7a4poJidbrWxUgbJvoYanMf1tIBuqYESe4HbgmhJUs31EsVR7zwl41mqgce4S7cE59XnemZLVHOLFZNDlemctIWntIYArgbefQ1Mp35TlvUI03dvFlSNApnxrt7NUHhBS5SnUw6DqtGGiSmSzDulGBso0+6OWfidW8wPUGL8FiVua1c+Nhvv0lAwhiLInv1ouMJeWtMvFu2zHqpqcAzRGPMJ8qtvIt7NrEQeJb2eZpzSYh5MO7cDVtyQhVxKxjfaFAZzvocdheEA96EleL1BMCxrqNuJtDIykvVwEpODSoiOYWM/VWbxQWqSmhydwDvHOzBAUOId584nEdoyQXETxbsqEjat847oNc5LrlvB4aZ5bCyNeyPrDAvUrvCjf3XSuZNZj9sByv2U8NHlBSOeYFYYBuffz5u1npkvmJo9rini+0JCF7LkSW7OPFmhK4bwrdivdeltl5CWhGiitPmeppB1NlLKKQ8chmDZAB/IfWx/vYD2438X0/+nYpxtWNQnd3gO8RLev8h8GHpyeZb+UNsfo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
